-- Role: ochat_user
-- DROP ROLE IF EXISTS ochat;

CREATE ROLE ochat WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:uJo9hgH45IjdfQFaCoPuJQ==$vcuLTq0JIv55pOm1gDVa9wTbtpNZ4Gf9P56TgyM3uig=:/yKUMC223C+Vr7H0ATYruRTY81uiJuiSTzdIGcn/pcw=';