server:
  address: 192.168.0.103
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            redirect-uri: http://87.92.27.149:8080/login/oauth2/code/github
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

#logging:
#  level:
#    org.springframework.security: DEBUG
