spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ea9ef14009d134e8faf3
            client-secret: 0212d23caf2215ac08f26b4f43f9bc9f5c27f350
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
          ochat:
            client-id: ochat
            client-secret: ZV8uwJFoIMCym3cQSxt3r80bmG3pzKJC
            client-name: OChat
            redirect-uri: http://localhost:8080/login/oauth2/code/ochat
            authorization-grant-type: authorization_code
            scope: openid
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/OChat

logging:
  level:
    org.springframework.security: DEBUG
