server:
  address: localhost #192.168.0.103
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          ochat:
            client-id: ochat
            client-secret: ZV8uwJFoIMCym3cQSxt3r80bmG3pzKJC
            client-name: OChat
            redirect-uri: http://localhost:8080/login/oauth2/code/ochat
            authorization-grant-type: authorization_code
            scope: openid
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/OChat

logging:
  level:
    org.springframework.security: DEBUG
